# Generated by Django 4.2.2 on 2023-06-28 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('available', models.BooleanField()),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_lectures.dean')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_lectures.student')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
