# Generated by Django 4.2.2 on 2023-06-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
